### PR TITLE
add boolean NodesSelectedByDefault for jobdetails

### PR DESCRIPTION
**Pull request by BobVanB**
I would like to have nodesSelectedByDefault added to the go-rundeck-api.
I am currently working on the terraform/rundeck provider, that will come after.

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @BobVanB! Thanks for this.

I wasn't able to find a reference to this attribute in the job-xml docs. Is this something new in a recent version of Rundeck? Do you have a link to some docs so I can understand what this does?

Thanks again!

**Comment by BobVanB** [comment]
This option is selected to force the user to chose a node.
What i did was exporting a job to xml in rundeck and then retrieve the parameter that was set.
I am currently not @ work, will get back to you tomorrow morning.

**Comment by BobVanB** [comment]
Hi @apparentlymart

Use It > Break It > Fix It > Pull It

I was working from an assumption that terraform builds a job xml and then 'import' this job definition to rundeck.

The option is enabled in the gui, by selecting:
- Nodes: Dispatch to Nodes Execute locally 

This will add this option:
Node selection
- Target nodes are selected by default
- The user has to explicitly select target nodes

I got the terraform-rundeck part working, noticed that this one is always set.
This is something i don't want. Today i will make the option optional, so that it only is checked when i add it to the terraform resource.

i noticed that if i set this option in the JobDetails, there is always a value present.
And terraform will always set the value, this is something i dont want. I just want to set / check the option when i add it to the terraform resource (main.tf). 

And beyond that, this option is not found in the terraform.tfstate, will also have to find a way to add it to this state, if thats possible at all.

I still got some figuring out to do.

I export the project and open the job-xml to see what is added.
Apparently when i enable the option dispatch to nodes, the options nodesSelectedByDefault is added to the job definition. Along with more options.
After that this is never removed again from the xml
xml default:

``` xml
<joblist>
    <job>
        <description></description>
        <executionEnabled>true</executionEnabled>
        <id>cfc4b929-09ed-4ba2-b77d-9e22e45a730a</id>
        <loglevel>INFO</loglevel>
        <name>TestJob</name>
        <scheduleEnabled>true</scheduleEnabled>
        <sequence keepgoing='false' strategy='node-first'>
            <command>
                <exec>echo command</exec>
            </command>
        </sequence>
        <uuid>cfc4b929-09ed-4ba2-b77d-9e22e45a730a</uuid>
    </job>
</joblist>
```

xml with dispatch to nodes enabled:

``` xml
<joblist>
    <job>
        <description></description>
        <dispatch>
            <excludePrecedence>true</excludePrecedence>
            <keepgoing>false</keepgoing>
            <rankOrder>ascending</rankOrder>
            <threadcount>1</threadcount>
        </dispatch>
        <executionEnabled>true</executionEnabled>
        <id>cfc4b929-09ed-4ba2-b77d-9e22e45a730a</id>
        <loglevel>INFO</loglevel>
        <name>TestJob</name>
        <nodefilters>
            <filter>.+</filter>
        </nodefilters>
        <nodesSelectedByDefault>true</nodesSelectedByDefault>
        <scheduleEnabled>true</scheduleEnabled>
        <sequence keepgoing='false' strategy='node-first'>
            <command>
                <exec>echo command</exec>
            </command>
        </sequence>
        <uuid>cfc4b929-09ed-4ba2-b77d-9e22e45a730a</uuid>
    </job>
</joblist>
```

**Comment by BobVanB** [comment]
Also just to make shure, the option is toggable when i use job import.

**Comment by BobVanB** [comment]
In the mean time, got the terraform code working.
Pull request will come after this pull.

Code for terraform:
https://github.com/hashicorp/terraform/compare/master...BobVanB:nodes_selected_by_default

**Comment by apparentlymart** [comment]
Thanks for this, and for the detailed description of it, @BobVanB!

Note that Terraform has a vendored copy of this module, so you'll need to update the vendored copy as part of your PR there. There are some instructions for this in Terraform's contributor guide.

**Comment by BobVanB** [comment]
I know, the vendor copy was breaking my head over why it wasn't working.
Already made a private build of terraform for my company, more features are needed.
Like the scheduling, and some other easy features. But that will be another pull request, thanks for your fast reply.

Kind regards,
Bob.

**Pull request merged**
