### PR TITLE
add omitempty to job detail fields

### PR DESCRIPTION
**Pull request by BigAirJosh**
add omitempty to the following fields executionEnabled, nodesSelectedByDefault and scheduleEnabled

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @BigAirJosh,

Adding `omitempty` to the `bool` fields would cause them to be included only when they are set to `true`, while today they are always included. Is there a particular reason why you want to exclude these when `false`, or is this just a cosmetic thing?

**Comment by BigAirJosh** [comment]
Thanks @apparentlymart  for the speedy reply,

We would like to be able to apply these settings manually and not have them overridden when our (terraform) provisioner reapplies the config.  Could this be the wrong approach to achieving this?

**Comment by BigAirJosh** [comment]
Perhaps we should wrap these with the same Boolean struct used by NodesSelectedByDefault as well as make them omitempty?

**Comment by apparentlymart** [comment]
Ahh, I see... you want to make these settings basically "tri-state", where `true`, `false` and unspecified are all distinct.

In that case, it does seem like the `*Boolean` type may be the answer here, allowing a `nil` value (in Go) to be considered the "empty" state to omit.

Unfortunately that would solve the problem only at this client library layer. Terraform _itself_ cannot, in the current version, represent an "unset" boolean value, and so Terraform would still explicitly set this to either `true` or `false`. Usually for Terraform this is desirable behavior since its goal is to make the underlying resources exactly match the configuration. Perhaps using [Terraform's `ignore_changes` feature](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) would help get the result you are looking for here, so that Terraform will populate an _initial_ value for these fields but will then not try to override it in case it changes outside of Terraform.

**Pull request closed without merging**
